name: 'Setup OKD OpenShift Cluster'
description: 'This action sets up an OKD OpenShift Cluster in your environment'
author: 'Marc Nuri'
branding:
  icon: circle
  color: red
inputs:
  oc version:
    description: 'Version of OKD OpenShift to deploy'
    required: true
  dns ip:
    description: 'External DNS server IP to use in node-config.yaml'
  enable:
    description: 'A list of components to enable (comma separated)'
  github token:
    description: 'GITHUB_TOKEN to be able to perform requests to GH REST API (with no limit)'
runs:
  using: 'node16'
  main: 'src/index.js'
