name: Perform checks

on: [push]

jobs:
  main:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: NPM install
        run: npm install
      - name: NPM test
        run: npm test
