name: Run action and validate environment

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    name: Run with dnsIp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.11.0,v3.9.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Test Action
        uses: ./
        with:
          oc version: ${{ matrix.openshift }}
          dns ip: 1.1.1.1
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate environment + Internet Access + DNS
        run: |
          cat /home/runner/work/actions-setup-openshift/actions-setup-openshift/openshift.local.clusterup/node/node-config.yaml || true
          cat /home/runner/work/actions-setup-openshift/actions-setup-openshift/openshift.local.clusterup/kubedns/resolv.conf || true
          oc run ubi --image=registry.access.redhat.com/ubi8/ubi-minimal --restart=Never -- sh -c 'sleep 3600'
          while (echo && oc get pods | grep -v -E "(Running|Completed|STATUS)");do sleep 5; done
          oc exec ubi -- cat /etc/resolv.conf
          oc exec ubi -- curl google.com
  run-with-components:
    name: Run with Components + dnsIp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Test Action
        uses: ./
        with:
          oc version: ${{ matrix.openshift }}
          dns ip: 1.1.1.1
          github token: ${{ secrets.GITHUB_TOKEN }}
          enable: 'service-catalog,registry,-web-console,-router,-persistent-volumes,-sample-templates'
      - name: Validate components
        run: |
          oc api-resources | grep 'servicecatalog.k8s.io'
