name: Run action and validate environment

on: [push]

jobs:
  main:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Run Action
        run: export INPUT_OC_VERSION="v3.11.0" && export INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN  }} && node src/index.js
      - name: Validate environment
        run: oc cluster status
